export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  BILLING_PLAN_INVALID: "BILLING_PLAN_INVALID",
  BILLING_NOT_CONFIGURED: "BILLING_NOT_CONFIGURED",
  BILLING_PROVIDER_ERROR: "BILLING_PROVIDER_ERROR",
  BILLING_WEBHOOK_SIGNATURE_INVALID: "BILLING_WEBHOOK_SIGNATURE_INVALID",
  ENTITLEMENT_EXCEEDED: "ENTITLEMENT_EXCEEDED",
  AI_PROVIDER_ERROR: "AI_PROVIDER_ERROR",
  AI_FLOW_FAILED: "AI_FLOW_FAILED",
  REVISION_NOT_APPLICABLE: "REVISION_NOT_APPLICABLE",
  SUGGESTION_NOT_APPLICABLE: "SUGGESTION_NOT_APPLICABLE",
  EXPORT_GENERATION_FAILED: "EXPORT_GENERATION_FAILED",
  EXPORT_STORAGE_FAILED: "EXPORT_STORAGE_FAILED",
  EXPORT_NOT_READY: "EXPORT_NOT_READY",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
