import { useEffect, useState } from "react";
import { Link, useLocation, useSearchParams } from "react-router";
import { getPrivacyConfig, NOTICE_VERSION, openPrivacyChoices, type PrivacyConfig } from "../integration/privacy";
import "../components/privacy.css";

export default function PrivacyNotice() {
  const [params, setParams] = useSearchParams(); const tr = params.get("lang") === "tr";
  const cookies = useLocation().pathname === "/cookies";
  const [config, setConfig] = useState<PrivacyConfig | null>(null);
  const [failed, setFailed] = useState(false);
  useEffect(() => { let active = true; void getPrivacyConfig().then(value => { if (active) setConfig(value); }).catch(() => { if (active) setFailed(true); }); return () => { active = false; }; }, []);
  return <main className="privacy-document">
    <Link to="/guided-journey">{config?.brand || "JobSpecificCV"}</Link>
    <div className="privacy-actions"><button onClick={() => setParams({ lang: tr ? "en" : "tr" })}>{tr ? "English" : "Türkçe"}</button></div>
    <h1>{cookies ? tr ? "Çerezler ve tarayıcı depolaması" : "Cookies and browser storage" : tr ? "Gizlilik ve KVKK aydınlatma metni" : "Privacy notice"}</h1>
    <p>{tr ? "Metin sürümü" : "Notice version"}: {NOTICE_VERSION}</p>
    {!config?.collection_enabled && <p role="status">{tr ? "İşletme ve veri işleme düzenlemeleri henüz doğrulanmadığı için yeni CV yükleme kapalıdır." : "New CV uploads are disabled until operator details and processing arrangements have been verified."}</p>}
    {failed && <p role="alert">{tr ? "İşletme bilgileri alınamadı. Lütfen tekrar deneyin." : "Operator details could not be loaded. Please try again."}</p>}
    {cookies ? <>
      <h2>{tr ? "Zorunlu depolama" : "Essential storage"}</h2>
      <p>{tr ? "Supabase oturum depolaması girişinizi korur. cv-builder:guest-import yalnızca geçici yükleme kimliği, erişim anahtarı, sona erme zamanı ve adım bilgilerini tutar. CV metni veya anket cevapları tarayıcıda saklanmaz. Erişim 24 saat sonra sona erer. Açık sayfa sona eren bilgileri temizler; kapalı tarayıcıdaki kayıt bir sonraki ziyarete veya tarayıcıdan silinmesine kadar kalabilir." : "Supabase authentication storage keeps you signed in. cv-builder:guest-import stores only a temporary upload ID, access token, expiry and progress. It does not store CV text or survey answers. Guest access expires after 24 hours. An open page clears expired recovery data; when the browser is closed, the record may remain until your next visit or browser clearing."}</p>
      <p>{tr ? "cv-builder:privacy-choices tercihinizi ve metin sürümünü 180 gün hatırlar. Arayüz tercihleri ayrıca cihazınızda saklanabilir. Zorunlu kurtarma verileri reklam veya izleme için kullanılmaz." : "cv-builder:privacy-choices remembers your analytics choice and notice version for 180 days. Interface preferences may also be stored on your device. Essential recovery data is not used for advertising or tracking."}</p>
      <h2>{tr ? "İsteğe bağlı analiz" : "Optional analytics"}</h2>
      <p>{tr ? "Google Analytics yalnızca kabulünüzden sonra yüklenir. Google'ın _ga çerezleri ziyaret ölçümü için kullanılabilir. Reklam kişiselleştirmesi ve Google Signals kapalıdır. CV içeriği, cevaplar, dosya adları ve hesap kimlikleri analiz olaylarına dahil edilmez. Reddetmeniz CV oluşturmayı engellemez. Global Privacy Control sinyali ret olarak uygulanır." : "Google Analytics loads only after acceptance. Google's _ga cookies may be used for visit measurement. Advertising personalization and Google Signals are disabled. CV content, answers, filenames and account identifiers are excluded from analytics events. Rejection does not prevent CV building. Global Privacy Control is treated as rejection."}</p>
      <p>{tr ? "İzni geri çekmek gelecekteki takibi durdurur ve bize ait analiz çerezlerini ve atıf depolamasını temizler. Daha önce gönderilmiş veriler kendiliğinden geri alınamaz." : "Withdrawal stops future tracking and clears our analytics cookies and attribution storage. Data already transmitted cannot automatically be recalled."}</p>
      <button className="underline" onClick={openPrivacyChoices}>{tr ? "Gizlilik tercihlerini değiştir" : "Change privacy choices"}</button>
    </> : <>
      <h2>{tr ? "Veri sorumlusu ve iletişim" : "Controller and contact"}</h2>
      <p>{config?.controller || config?.brand || (tr ? "Henüz doğrulanmadı" : "Not yet verified")}<br/>{config?.country || ""}{config?.address && <><br/>{config.address}</>}<br/>{config?.contact ? <a href={`mailto:${config.contact}`}>{config.contact}</a> : tr ? "Gizlilik iletişim adresi henüz doğrulanmadı." : "Privacy contact has not yet been verified."}</p>
      <h2>{tr ? "Topladığımız veriler ve amaçlar" : "What we collect and why"}</h2>
      <p>{tr ? "Yüklediğiniz CV ve çıkarılan metin CV'nizi okumak, rehber niteliğinde bir puan hesaplamak ve düzenleyiciyi hazırlamak için işlenir. Kaydolduğunuzda kimlik ve profil bilgileriniz hesabınızı yönetmek için kullanılır. İsteğe bağlı hedef, kariyer ve eğitim cevapları rehberliği kişiselleştirir; bunlar doğrulanmış CV bilgileri değildir. Bizi nereden duyduğunuz yalnızca istatistik amacı taşır, yapay zekâya gönderilmez. Misafir kimliği, CV ile bağlantılı verileri anonim hale getirmez." : "Your uploaded CV and extracted text are processed to read your CV, calculate a guidance score and prepare the editor. On signup, identity and profile information supports your account. Optional goal, career and education answers personalize guidance; they are not verified CV facts. Referral answers are for statistics and are not sent to AI. A guest ID does not make data linked to a CV anonymous."}</p>
      <h2>{tr ? "Hukuki dayanaklar ve tercihler" : "Legal bases and choices"}</h2>
      <p>{tr ? "Talep ettiğiniz temel hizmetin sağlanması için gerekli işlemler sözleşmenin kurulması veya ifası kapsamında değerlendirilir. İsteğe bağlı cevaplar, yapay zekâ ve analiz için ayrı ve bilgilendirilmiş tercihler kullanılır. Kanada merkezli işletmenin PIPEDA ve geçerli diğer kurallar kapsamındaki yükümlülükleri de yayına geçiş incelemesinde değerlendirilir. Güvenlik işlemlerinin meşru menfaat dayanağı ve zorunlu mali kayıtların yasal yükümlülük dayanağı işletmenin yayına geçiş incelemesinde doğrulanmalıdır. Aydınlatma metninin sunulması rıza talebi değildir." : "Processing necessary to provide the service you request is assessed under entering into or performing a contract. Optional answers, AI and analytics use separate informed choices. The Canada-based operator’s obligations under PIPEDA and other applicable rules are also assessed in the launch review. Legitimate interests for security and legal obligations for required financial records must be verified in the business launch review. Providing this notice is not a request for blanket consent."}</p>
      <h2>{tr ? "Hizmet sağlayıcılar ve uluslararası aktarımlar" : "Providers and international transfers"}</h2>
      <p>{tr ? "Supabase kimlik doğrulama ve depolama, Vercel barındırma, Stripe ödeme hizmeti sağlar. Kabul ederseniz Google Analytics ölçüm için kullanılır. Bu sağlayıcılar, sözleşme ve altyapılarına göre başka ülkelerde veri işleyebilir. İşletme, geçerli KVKK, AB ve Birleşik Krallık aktarım güvencelerini doğrulamadan yeni veri toplamayı etkinleştiremez." : "Supabase provides authentication and storage, Vercel hosts the service, and Stripe handles payments. Google Analytics provides measurement if accepted. These providers may process data in other countries depending on their contracts and infrastructure. The operator must verify applicable Turkish, EU and UK transfer safeguards before enabling new collection."}</p>
      {config?.hosting_region && <p>{tr ? "Bildirilen birincil veritabanı ve uygulama barındırma bölgesi" : "Declared primary database and application hosting region"}: {config.hosting_region}. {tr ? "Bu bilgi, tüm sağlayıcı işlemlerinin veya yapay zekâ işlemlerinin yalnızca bu ülkede gerçekleştiği anlamına gelmez." : "This does not mean that all provider operations or AI processing occur only in this country."}</p>}
      {config?.processors?.map(provider => <p key={provider.id}><strong>{provider.name}</strong>: {provider.purpose}<br/>{tr ? "Ülkeler" : "Countries"}: {provider.countries}<br/>{tr ? "Saklama" : "Retention"}: {provider.retention}<br/>{tr ? "Aktarım güvenceleri" : "Transfer safeguards"}: {provider.safeguards}</p>)}
      <h2>{tr ? "Yapay zekâ" : "AI processing"}</h2>
      <p>{tr ? "Yapılandırılan sağlayıcı" : "Configured provider"}: {config?.ai_provider || (tr ? "Alınıyor…" : "Loading…")}. {tr ? "Yapay zekâyı etkinleştirirseniz ilgili CV metni, görev talimatı ve uygun kişiselleştirme bağlamı sağlayıcıya gönderilebilir. İzin yoksa harici yapay zekâ kullanılmaz. İzni hesap gizlilik ayarlarından geri çekebilirsiniz. Daha önce iletilen bilgi kendiliğinden geri alınamaz. Gereksiz sağlık, din veya üçüncü kişi bilgilerini yüklemeyin. CV puanı işe alınma garantisi veya bir işe alım kararı değildir." : "If you enable AI, relevant CV text, task instructions and applicable personalization context may be sent to this provider. Without permission, external AI is not used. Withdraw permission in account privacy settings. Already transmitted information cannot automatically be recalled. Avoid unnecessary health, religious or third-party information. The CV score is guidance, not an employment guarantee or hiring decision."}</p>
      {config?.ai_required !== false && <p>{tr ? "JobSpecificCV yapay zekâ destekli bir CV hizmetidir. CV yükleme, analiz ve düzenleyici deneyimine devam etmek için yapay zekâ işlemeyi etkinleştirmeniz gerekir. Reddederseniz hiçbir harici yapay zekâ işlemi başlatılmaz; yükleme öncesinde veya hesap gizlilik ayarlarından daha sonra etkinleştirebilirsiniz. İzni geri çekmek CV deneyimini duraklatır; gizlilik ayarları, veri indirme, abonelik yönetimi ve silme kontrolleri açık kalır. Analiz izni ayrı ve isteğe bağlıdır." : "JobSpecificCV is an AI-powered CV service. Enable AI processing to continue with upload, analysis and the editor experience. If you decline, no external AI processing starts; you can enable it later before upload or in account privacy settings. Withdrawal pauses the CV experience; privacy settings, data download, subscription management and deletion controls remain available. Analytics permission is separate and optional."}</p>}
      <h2>{tr ? "Saklama ve silme" : "Retention and deletion"}</h2>
      <p>{tr ? "Misafir yüklemesini 24 saat içinde kurtarabilirsiniz; sona eren yüklemeler günlük temizlikte silinir. Fiziksel silme, hata halinde yeniden deneme gerektirebilir. Hesabınıza kaydedilen CV ve profil verileri hizmeti sağlamak için tutulur ve silme talebiniz üzerine kaldırılır; işletme saklama gerekliliğini düzenli olarak gözden geçirir. Dosyaları ve hesabınızı silme kontrolleri mevcuttur. Veri indirme arşivleri 24 saatte sona erer, bağlantıları en fazla beş dakika geçerlidir." : "Recover a guest upload within 24 hours; expired uploads are removed during daily cleanup. Physical deletion may require retries if an operation fails. Account CV and profile data is retained to provide the service and removed on deletion request; the operator regularly reviews continued retention needs. Upload and account deletion controls are available. Data-export archives expire after 24 hours and download links last at most five minutes."}</p>
      <p>{tr ? "Geri çekilen izin kanıtları sınırlı uyum erişimiyle 12 ay, silme kayıtları 90 gün tutulur. Ham yapay zekâ hata tanılama verisi aktif işlemler dışında yedi gün sonra temizlenir. Operasyon kayıtları için 14 günlük hedef barındırma ayarlarında doğrulanır. Yedekler sağlayıcının doğrulanmış süresinde sona erer; geri yüklemede silmeler tekrar uygulanmalıdır. Yasal mali kayıtlar ayrı saklanabilir. Bu süreler yasal olarak zorunlu evrensel süreler değil, incelemeye tabi ürün politikalarıdır." : "Withdrawn permission evidence is retained for 12 months with restricted compliance access; erasure records for 90 days. Raw AI diagnostics are scrubbed after seven days, excluding active work. A 14-day operational-log target must be verified in hosting settings. Backups expire under the provider's verified schedule; deletions must be reapplied on restoration. Legally required financial records may be retained separately. These are reviewed product policies, not universal statutory periods."}</p>
      <h2>{tr ? "Haklarınız" : "Your rights"}</h2>
      <p>{tr ? "Geçerli hukuka göre erişim, düzeltme, silme, taşınabilirlik, kısıtlama, itiraz, rızayı geri çekme ve yetkili makama şikâyet haklarınız olabilir. Hesap ayarlarınızdan verilerinizi indirin, cevaplarınızı temizleyin veya hesabınızı silin. Diğer talepler ve hesap erişimi kaybı için yukarıdaki gizlilik adresine yazın. Kimlik doğrulaması gerekebilir; dahili yanıt hedefi 30 gündür. Her hakkın kapsamı geçerli hukuka göre değişir." : "Depending on applicable law, you may have rights to access, correction, erasure, portability, restriction, objection, consent withdrawal and complaints to the appropriate authority. Use account settings to download data, clear answers or delete your account. Contact the privacy address above for other requests or lost account access. Identity verification may be required; our internal response target is 30 days. The scope of each right depends on applicable law."}</p>
    </>}
    <p><Link to={cookies ? "/privacy" : "/cookies"}>{cookies ? tr ? "Gizlilik metni" : "Privacy notice" : tr ? "Çerezler ve depolama" : "Cookies and storage"}</Link></p>
  </main>;
}
