-- Six Signature layout families, each with three coordinated palettes.
insert into public.cv_templates (name, slug, status, module_type, preview_config, export_config)
values
  ('Studio', 'studio-banner', 'active', 'standard',
   '{"preview":"v3","theme":"signature","family":"studio-banner","palette":"teal","badges":["New","Signature"]}'::jsonb,
   '{"pdf":{"enabled":true},"docx":{"enabled":true}}'::jsonb),
  ('Studio Ocean', 'studio-banner-ocean', 'active', 'standard',
   '{"preview":"v3","theme":"signature","family":"studio-banner","palette":"ocean","badges":["New","Signature"]}'::jsonb,
   '{"pdf":{"enabled":true},"docx":{"enabled":true}}'::jsonb),
  ('Studio Terracotta', 'studio-banner-terracotta', 'active', 'standard',
   '{"preview":"v3","theme":"signature","family":"studio-banner","palette":"terracotta","badges":["New","Signature"]}'::jsonb,
   '{"pdf":{"enabled":true},"docx":{"enabled":true}}'::jsonb),
  ('Editorial', 'editorial-index', 'active', 'standard',
   '{"preview":"v3","theme":"signature","family":"editorial-index","palette":"plum","badges":["New","Signature"]}'::jsonb,
   '{"pdf":{"enabled":true},"docx":{"enabled":true}}'::jsonb),
  ('Editorial Forest', 'editorial-index-forest', 'active', 'standard',
   '{"preview":"v3","theme":"signature","family":"editorial-index","palette":"forest","badges":["New","Signature"]}'::jsonb,
   '{"pdf":{"enabled":true},"docx":{"enabled":true}}'::jsonb),
  ('Editorial Graphite', 'editorial-index-graphite', 'active', 'standard',
   '{"preview":"v3","theme":"signature","family":"editorial-index","palette":"graphite","badges":["New","Signature"]}'::jsonb,
   '{"pdf":{"enabled":true},"docx":{"enabled":true}}'::jsonb),
  ('Horizon', 'horizon-rail', 'active', 'standard',
   '{"preview":"v3","theme":"signature","family":"horizon-rail","palette":"navy","badges":["New","Signature"]}'::jsonb,
   '{"pdf":{"enabled":true},"docx":{"enabled":true}}'::jsonb),
  ('Horizon Forest', 'horizon-rail-forest', 'active', 'standard',
   '{"preview":"v3","theme":"signature","family":"horizon-rail","palette":"forest","badges":["New","Signature"]}'::jsonb,
   '{"pdf":{"enabled":true},"docx":{"enabled":true}}'::jsonb),
  ('Horizon Plum', 'horizon-rail-plum', 'active', 'standard',
   '{"preview":"v3","theme":"signature","family":"horizon-rail","palette":"plum","badges":["New","Signature"]}'::jsonb,
   '{"pdf":{"enabled":true},"docx":{"enabled":true}}'::jsonb),
  ('Mosaic', 'mosaic-columns', 'active', 'standard',
   '{"preview":"v3","theme":"signature","family":"mosaic-columns","palette":"ocean","badges":["New","Signature"]}'::jsonb,
   '{"pdf":{"enabled":true},"docx":{"enabled":true}}'::jsonb),
  ('Mosaic Rose', 'mosaic-columns-rose', 'active', 'standard',
   '{"preview":"v3","theme":"signature","family":"mosaic-columns","palette":"rose","badges":["New","Signature"]}'::jsonb,
   '{"pdf":{"enabled":true},"docx":{"enabled":true}}'::jsonb),
  ('Mosaic Graphite', 'mosaic-columns-graphite', 'active', 'standard',
   '{"preview":"v3","theme":"signature","family":"mosaic-columns","palette":"graphite","badges":["New","Signature"]}'::jsonb,
   '{"pdf":{"enabled":true},"docx":{"enabled":true}}'::jsonb),
  ('Ledger', 'ledger-split', 'active', 'standard',
   '{"preview":"v3","theme":"signature","family":"ledger-split","palette":"terracotta","badges":["New","Signature"]}'::jsonb,
   '{"pdf":{"enabled":true},"docx":{"enabled":true}}'::jsonb),
  ('Ledger Teal', 'ledger-split-teal', 'active', 'standard',
   '{"preview":"v3","theme":"signature","family":"ledger-split","palette":"teal","badges":["New","Signature"]}'::jsonb,
   '{"pdf":{"enabled":true},"docx":{"enabled":true}}'::jsonb),
  ('Ledger Plum', 'ledger-split-plum', 'active', 'standard',
   '{"preview":"v3","theme":"signature","family":"ledger-split","palette":"plum","badges":["New","Signature"]}'::jsonb,
   '{"pdf":{"enabled":true},"docx":{"enabled":true}}'::jsonb),
  ('Contour', 'contour-cards', 'active', 'standard',
   '{"preview":"v3","theme":"signature","family":"contour-cards","palette":"rose","badges":["New","Signature"]}'::jsonb,
   '{"pdf":{"enabled":true},"docx":{"enabled":true}}'::jsonb),
  ('Contour Cobalt', 'contour-cards-cobalt', 'active', 'standard',
   '{"preview":"v3","theme":"signature","family":"contour-cards","palette":"cobalt","badges":["New","Signature"]}'::jsonb,
   '{"pdf":{"enabled":true},"docx":{"enabled":true}}'::jsonb),
  ('Contour Forest', 'contour-cards-forest', 'active', 'standard',
   '{"preview":"v3","theme":"signature","family":"contour-cards","palette":"forest","badges":["New","Signature"]}'::jsonb,
   '{"pdf":{"enabled":true},"docx":{"enabled":true}}'::jsonb)
on conflict (slug) do update set
  name = excluded.name, status = excluded.status, module_type = excluded.module_type,
  preview_config = excluded.preview_config, export_config = excluded.export_config, updated_at = now();
